spring:
  application:
    name: store
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 9000
    refreshTokenExpiration: 604800
  profiles:
    active: dev
stripe:
  secretKey: ${STRIPE_SECRET}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET}



