spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Durga@03
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 9000
    refreshTokenExpiration: 604800
stripe:
  secretKey: ${STRIPE_SECRET}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET}
webUrl: http://localhost:4242



